// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mosque-dashboard.proto

package com.mujeeb.mosquedashboard.grpc;

/**
 * Protobuf type {@code com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest}
 */
@SuppressWarnings("deprecation")
public final class GetDataForMobileAppRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest)
    GetDataForMobileAppRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetDataForMobileAppRequest.newBuilder() to construct.
  private GetDataForMobileAppRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetDataForMobileAppRequest() {
    hijriMonth_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetDataForMobileAppRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetDataForMobileAppRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.mujeeb.mosquedashboard.grpc.NamazTime.Builder subBuilder = null;
            if (fajrTime_ != null) {
              subBuilder = fajrTime_.toBuilder();
            }
            fajrTime_ = input.readMessage(com.mujeeb.mosquedashboard.grpc.NamazTime.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(fajrTime_);
              fajrTime_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.mujeeb.mosquedashboard.grpc.NamazTime.Builder subBuilder = null;
            if (zuhrTime_ != null) {
              subBuilder = zuhrTime_.toBuilder();
            }
            zuhrTime_ = input.readMessage(com.mujeeb.mosquedashboard.grpc.NamazTime.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(zuhrTime_);
              zuhrTime_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.mujeeb.mosquedashboard.grpc.NamazTime.Builder subBuilder = null;
            if (asrTime_ != null) {
              subBuilder = asrTime_.toBuilder();
            }
            asrTime_ = input.readMessage(com.mujeeb.mosquedashboard.grpc.NamazTime.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(asrTime_);
              asrTime_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.mujeeb.mosquedashboard.grpc.NamazTime.Builder subBuilder = null;
            if (ishaTime_ != null) {
              subBuilder = ishaTime_.toBuilder();
            }
            ishaTime_ = input.readMessage(com.mujeeb.mosquedashboard.grpc.NamazTime.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(ishaTime_);
              ishaTime_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            com.mujeeb.mosquedashboard.grpc.NamazTime.Builder subBuilder = null;
            if (jumuaTime_ != null) {
              subBuilder = jumuaTime_.toBuilder();
            }
            jumuaTime_ = input.readMessage(com.mujeeb.mosquedashboard.grpc.NamazTime.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(jumuaTime_);
              jumuaTime_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            com.mujeeb.mosquedashboard.grpc.NamazTime.Builder subBuilder = null;
            if (ishraqTime_ != null) {
              subBuilder = ishraqTime_.toBuilder();
            }
            ishraqTime_ = input.readMessage(com.mujeeb.mosquedashboard.grpc.NamazTime.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(ishraqTime_);
              ishraqTime_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            com.mujeeb.mosquedashboard.grpc.NamazTime.Builder subBuilder = null;
            if (duhaTime_ != null) {
              subBuilder = duhaTime_.toBuilder();
            }
            duhaTime_ = input.readMessage(com.mujeeb.mosquedashboard.grpc.NamazTime.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(duhaTime_);
              duhaTime_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            com.mujeeb.mosquedashboard.grpc.NamazTime.Builder subBuilder = null;
            if (suhurTime_ != null) {
              subBuilder = suhurTime_.toBuilder();
            }
            suhurTime_ = input.readMessage(com.mujeeb.mosquedashboard.grpc.NamazTime.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(suhurTime_);
              suhurTime_ = subBuilder.buildPartial();
            }

            break;
          }
          case 74: {
            com.mujeeb.mosquedashboard.grpc.NamazTime.Builder subBuilder = null;
            if (iftarTime_ != null) {
              subBuilder = iftarTime_.toBuilder();
            }
            iftarTime_ = input.readMessage(com.mujeeb.mosquedashboard.grpc.NamazTime.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(iftarTime_);
              iftarTime_ = subBuilder.buildPartial();
            }

            break;
          }
          case 82: {
            com.mujeeb.mosquedashboard.grpc.NamazTime.Builder subBuilder = null;
            if (screenSaverOnTime_ != null) {
              subBuilder = screenSaverOnTime_.toBuilder();
            }
            screenSaverOnTime_ = input.readMessage(com.mujeeb.mosquedashboard.grpc.NamazTime.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(screenSaverOnTime_);
              screenSaverOnTime_ = subBuilder.buildPartial();
            }

            break;
          }
          case 90: {
            com.mujeeb.mosquedashboard.grpc.NamazTime.Builder subBuilder = null;
            if (screenSaverOffTime_ != null) {
              subBuilder = screenSaverOffTime_.toBuilder();
            }
            screenSaverOffTime_ = input.readMessage(com.mujeeb.mosquedashboard.grpc.NamazTime.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(screenSaverOffTime_);
              screenSaverOffTime_ = subBuilder.buildPartial();
            }

            break;
          }
          case 96: {

            hijriAdjustment_ = input.readInt32();
            break;
          }
          case 104: {

            hijriDate_ = input.readInt32();
            break;
          }
          case 114: {
            java.lang.String s = input.readStringRequireUtf8();

            hijriMonth_ = s;
            break;
          }
          case 120: {

            hijriYear_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
//      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mujeeb.mosquedashboard.grpc.MosqueDashboardProto.internal_static_com_mujeeb_mosquedashboard_grpc_GetDataForMobileAppRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mujeeb.mosquedashboard.grpc.MosqueDashboardProto.internal_static_com_mujeeb_mosquedashboard_grpc_GetDataForMobileAppRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest.class, com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest.Builder.class);
  }

  public static final int FAJRTIME_FIELD_NUMBER = 1;
  private com.mujeeb.mosquedashboard.grpc.NamazTime fajrTime_;
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime fajrTime = 1;</code>
   * @return Whether the fajrTime field is set.
   */
  @java.lang.Override
  public boolean hasFajrTime() {
    return fajrTime_ != null;
  }
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime fajrTime = 1;</code>
   * @return The fajrTime.
   */
  @java.lang.Override
  public com.mujeeb.mosquedashboard.grpc.NamazTime getFajrTime() {
    return fajrTime_ == null ? com.mujeeb.mosquedashboard.grpc.NamazTime.getDefaultInstance() : fajrTime_;
  }
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime fajrTime = 1;</code>
   */
  @java.lang.Override
  public com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder getFajrTimeOrBuilder() {
    return getFajrTime();
  }

  public static final int ZUHRTIME_FIELD_NUMBER = 2;
  private com.mujeeb.mosquedashboard.grpc.NamazTime zuhrTime_;
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime zuhrTime = 2;</code>
   * @return Whether the zuhrTime field is set.
   */
  @java.lang.Override
  public boolean hasZuhrTime() {
    return zuhrTime_ != null;
  }
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime zuhrTime = 2;</code>
   * @return The zuhrTime.
   */
  @java.lang.Override
  public com.mujeeb.mosquedashboard.grpc.NamazTime getZuhrTime() {
    return zuhrTime_ == null ? com.mujeeb.mosquedashboard.grpc.NamazTime.getDefaultInstance() : zuhrTime_;
  }
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime zuhrTime = 2;</code>
   */
  @java.lang.Override
  public com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder getZuhrTimeOrBuilder() {
    return getZuhrTime();
  }

  public static final int ASRTIME_FIELD_NUMBER = 3;
  private com.mujeeb.mosquedashboard.grpc.NamazTime asrTime_;
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime asrTime = 3;</code>
   * @return Whether the asrTime field is set.
   */
  @java.lang.Override
  public boolean hasAsrTime() {
    return asrTime_ != null;
  }
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime asrTime = 3;</code>
   * @return The asrTime.
   */
  @java.lang.Override
  public com.mujeeb.mosquedashboard.grpc.NamazTime getAsrTime() {
    return asrTime_ == null ? com.mujeeb.mosquedashboard.grpc.NamazTime.getDefaultInstance() : asrTime_;
  }
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime asrTime = 3;</code>
   */
  @java.lang.Override
  public com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder getAsrTimeOrBuilder() {
    return getAsrTime();
  }

  public static final int ISHATIME_FIELD_NUMBER = 4;
  private com.mujeeb.mosquedashboard.grpc.NamazTime ishaTime_;
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime ishaTime = 4;</code>
   * @return Whether the ishaTime field is set.
   */
  @java.lang.Override
  public boolean hasIshaTime() {
    return ishaTime_ != null;
  }
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime ishaTime = 4;</code>
   * @return The ishaTime.
   */
  @java.lang.Override
  public com.mujeeb.mosquedashboard.grpc.NamazTime getIshaTime() {
    return ishaTime_ == null ? com.mujeeb.mosquedashboard.grpc.NamazTime.getDefaultInstance() : ishaTime_;
  }
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime ishaTime = 4;</code>
   */
  @java.lang.Override
  public com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder getIshaTimeOrBuilder() {
    return getIshaTime();
  }

  public static final int JUMUATIME_FIELD_NUMBER = 5;
  private com.mujeeb.mosquedashboard.grpc.NamazTime jumuaTime_;
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime jumuaTime = 5;</code>
   * @return Whether the jumuaTime field is set.
   */
  @java.lang.Override
  public boolean hasJumuaTime() {
    return jumuaTime_ != null;
  }
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime jumuaTime = 5;</code>
   * @return The jumuaTime.
   */
  @java.lang.Override
  public com.mujeeb.mosquedashboard.grpc.NamazTime getJumuaTime() {
    return jumuaTime_ == null ? com.mujeeb.mosquedashboard.grpc.NamazTime.getDefaultInstance() : jumuaTime_;
  }
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime jumuaTime = 5;</code>
   */
  @java.lang.Override
  public com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder getJumuaTimeOrBuilder() {
    return getJumuaTime();
  }

  public static final int ISHRAQTIME_FIELD_NUMBER = 6;
  private com.mujeeb.mosquedashboard.grpc.NamazTime ishraqTime_;
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime ishraqTime = 6;</code>
   * @return Whether the ishraqTime field is set.
   */
  @java.lang.Override
  public boolean hasIshraqTime() {
    return ishraqTime_ != null;
  }
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime ishraqTime = 6;</code>
   * @return The ishraqTime.
   */
  @java.lang.Override
  public com.mujeeb.mosquedashboard.grpc.NamazTime getIshraqTime() {
    return ishraqTime_ == null ? com.mujeeb.mosquedashboard.grpc.NamazTime.getDefaultInstance() : ishraqTime_;
  }
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime ishraqTime = 6;</code>
   */
  @java.lang.Override
  public com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder getIshraqTimeOrBuilder() {
    return getIshraqTime();
  }

  public static final int DUHATIME_FIELD_NUMBER = 7;
  private com.mujeeb.mosquedashboard.grpc.NamazTime duhaTime_;
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime duhaTime = 7;</code>
   * @return Whether the duhaTime field is set.
   */
  @java.lang.Override
  public boolean hasDuhaTime() {
    return duhaTime_ != null;
  }
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime duhaTime = 7;</code>
   * @return The duhaTime.
   */
  @java.lang.Override
  public com.mujeeb.mosquedashboard.grpc.NamazTime getDuhaTime() {
    return duhaTime_ == null ? com.mujeeb.mosquedashboard.grpc.NamazTime.getDefaultInstance() : duhaTime_;
  }
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime duhaTime = 7;</code>
   */
  @java.lang.Override
  public com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder getDuhaTimeOrBuilder() {
    return getDuhaTime();
  }

  public static final int SUHURTIME_FIELD_NUMBER = 8;
  private com.mujeeb.mosquedashboard.grpc.NamazTime suhurTime_;
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime suhurTime = 8;</code>
   * @return Whether the suhurTime field is set.
   */
  @java.lang.Override
  public boolean hasSuhurTime() {
    return suhurTime_ != null;
  }
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime suhurTime = 8;</code>
   * @return The suhurTime.
   */
  @java.lang.Override
  public com.mujeeb.mosquedashboard.grpc.NamazTime getSuhurTime() {
    return suhurTime_ == null ? com.mujeeb.mosquedashboard.grpc.NamazTime.getDefaultInstance() : suhurTime_;
  }
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime suhurTime = 8;</code>
   */
  @java.lang.Override
  public com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder getSuhurTimeOrBuilder() {
    return getSuhurTime();
  }

  public static final int IFTARTIME_FIELD_NUMBER = 9;
  private com.mujeeb.mosquedashboard.grpc.NamazTime iftarTime_;
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime iftarTime = 9;</code>
   * @return Whether the iftarTime field is set.
   */
  @java.lang.Override
  public boolean hasIftarTime() {
    return iftarTime_ != null;
  }
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime iftarTime = 9;</code>
   * @return The iftarTime.
   */
  @java.lang.Override
  public com.mujeeb.mosquedashboard.grpc.NamazTime getIftarTime() {
    return iftarTime_ == null ? com.mujeeb.mosquedashboard.grpc.NamazTime.getDefaultInstance() : iftarTime_;
  }
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime iftarTime = 9;</code>
   */
  @java.lang.Override
  public com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder getIftarTimeOrBuilder() {
    return getIftarTime();
  }

  public static final int SCREENSAVERONTIME_FIELD_NUMBER = 10;
  private com.mujeeb.mosquedashboard.grpc.NamazTime screenSaverOnTime_;
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime screenSaverOnTime = 10;</code>
   * @return Whether the screenSaverOnTime field is set.
   */
  @java.lang.Override
  public boolean hasScreenSaverOnTime() {
    return screenSaverOnTime_ != null;
  }
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime screenSaverOnTime = 10;</code>
   * @return The screenSaverOnTime.
   */
  @java.lang.Override
  public com.mujeeb.mosquedashboard.grpc.NamazTime getScreenSaverOnTime() {
    return screenSaverOnTime_ == null ? com.mujeeb.mosquedashboard.grpc.NamazTime.getDefaultInstance() : screenSaverOnTime_;
  }
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime screenSaverOnTime = 10;</code>
   */
  @java.lang.Override
  public com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder getScreenSaverOnTimeOrBuilder() {
    return getScreenSaverOnTime();
  }

  public static final int SCREENSAVEROFFTIME_FIELD_NUMBER = 11;
  private com.mujeeb.mosquedashboard.grpc.NamazTime screenSaverOffTime_;
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime screenSaverOffTime = 11;</code>
   * @return Whether the screenSaverOffTime field is set.
   */
  @java.lang.Override
  public boolean hasScreenSaverOffTime() {
    return screenSaverOffTime_ != null;
  }
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime screenSaverOffTime = 11;</code>
   * @return The screenSaverOffTime.
   */
  @java.lang.Override
  public com.mujeeb.mosquedashboard.grpc.NamazTime getScreenSaverOffTime() {
    return screenSaverOffTime_ == null ? com.mujeeb.mosquedashboard.grpc.NamazTime.getDefaultInstance() : screenSaverOffTime_;
  }
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime screenSaverOffTime = 11;</code>
   */
  @java.lang.Override
  public com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder getScreenSaverOffTimeOrBuilder() {
    return getScreenSaverOffTime();
  }

  public static final int HIJRIADJUSTMENT_FIELD_NUMBER = 12;
  private int hijriAdjustment_;
  /**
   * <code>int32 hijriAdjustment = 12;</code>
   * @return The hijriAdjustment.
   */
  @java.lang.Override
  public int getHijriAdjustment() {
    return hijriAdjustment_;
  }

  public static final int HIJRIDATE_FIELD_NUMBER = 13;
  private int hijriDate_;
  /**
   * <code>int32 hijriDate = 13;</code>
   * @return The hijriDate.
   */
  @java.lang.Override
  public int getHijriDate() {
    return hijriDate_;
  }

  public static final int HIJRIMONTH_FIELD_NUMBER = 14;
  private volatile java.lang.Object hijriMonth_;
  /**
   * <code>string hijriMonth = 14;</code>
   * @return The hijriMonth.
   */
  @java.lang.Override
  public java.lang.String getHijriMonth() {
    java.lang.Object ref = hijriMonth_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hijriMonth_ = s;
      return s;
    }
  }
  /**
   * <code>string hijriMonth = 14;</code>
   * @return The bytes for hijriMonth.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHijriMonthBytes() {
    java.lang.Object ref = hijriMonth_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      hijriMonth_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HIJRIYEAR_FIELD_NUMBER = 15;
  private int hijriYear_;
  /**
   * <code>int32 hijriYear = 15;</code>
   * @return The hijriYear.
   */
  @java.lang.Override
  public int getHijriYear() {
    return hijriYear_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (fajrTime_ != null) {
      output.writeMessage(1, getFajrTime());
    }
    if (zuhrTime_ != null) {
      output.writeMessage(2, getZuhrTime());
    }
    if (asrTime_ != null) {
      output.writeMessage(3, getAsrTime());
    }
    if (ishaTime_ != null) {
      output.writeMessage(4, getIshaTime());
    }
    if (jumuaTime_ != null) {
      output.writeMessage(5, getJumuaTime());
    }
    if (ishraqTime_ != null) {
      output.writeMessage(6, getIshraqTime());
    }
    if (duhaTime_ != null) {
      output.writeMessage(7, getDuhaTime());
    }
    if (suhurTime_ != null) {
      output.writeMessage(8, getSuhurTime());
    }
    if (iftarTime_ != null) {
      output.writeMessage(9, getIftarTime());
    }
    if (screenSaverOnTime_ != null) {
      output.writeMessage(10, getScreenSaverOnTime());
    }
    if (screenSaverOffTime_ != null) {
      output.writeMessage(11, getScreenSaverOffTime());
    }
    if (hijriAdjustment_ != 0) {
      output.writeInt32(12, hijriAdjustment_);
    }
    if (hijriDate_ != 0) {
      output.writeInt32(13, hijriDate_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hijriMonth_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, hijriMonth_);
    }
    if (hijriYear_ != 0) {
      output.writeInt32(15, hijriYear_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (fajrTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getFajrTime());
    }
    if (zuhrTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getZuhrTime());
    }
    if (asrTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getAsrTime());
    }
    if (ishaTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getIshaTime());
    }
    if (jumuaTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getJumuaTime());
    }
    if (ishraqTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getIshraqTime());
    }
    if (duhaTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getDuhaTime());
    }
    if (suhurTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getSuhurTime());
    }
    if (iftarTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getIftarTime());
    }
    if (screenSaverOnTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getScreenSaverOnTime());
    }
    if (screenSaverOffTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, getScreenSaverOffTime());
    }
    if (hijriAdjustment_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(12, hijriAdjustment_);
    }
    if (hijriDate_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(13, hijriDate_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hijriMonth_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, hijriMonth_);
    }
    if (hijriYear_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(15, hijriYear_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest)) {
      return super.equals(obj);
    }
    com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest other = (com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest) obj;

    if (hasFajrTime() != other.hasFajrTime()) return false;
    if (hasFajrTime()) {
      if (!getFajrTime()
          .equals(other.getFajrTime())) return false;
    }
    if (hasZuhrTime() != other.hasZuhrTime()) return false;
    if (hasZuhrTime()) {
      if (!getZuhrTime()
          .equals(other.getZuhrTime())) return false;
    }
    if (hasAsrTime() != other.hasAsrTime()) return false;
    if (hasAsrTime()) {
      if (!getAsrTime()
          .equals(other.getAsrTime())) return false;
    }
    if (hasIshaTime() != other.hasIshaTime()) return false;
    if (hasIshaTime()) {
      if (!getIshaTime()
          .equals(other.getIshaTime())) return false;
    }
    if (hasJumuaTime() != other.hasJumuaTime()) return false;
    if (hasJumuaTime()) {
      if (!getJumuaTime()
          .equals(other.getJumuaTime())) return false;
    }
    if (hasIshraqTime() != other.hasIshraqTime()) return false;
    if (hasIshraqTime()) {
      if (!getIshraqTime()
          .equals(other.getIshraqTime())) return false;
    }
    if (hasDuhaTime() != other.hasDuhaTime()) return false;
    if (hasDuhaTime()) {
      if (!getDuhaTime()
          .equals(other.getDuhaTime())) return false;
    }
    if (hasSuhurTime() != other.hasSuhurTime()) return false;
    if (hasSuhurTime()) {
      if (!getSuhurTime()
          .equals(other.getSuhurTime())) return false;
    }
    if (hasIftarTime() != other.hasIftarTime()) return false;
    if (hasIftarTime()) {
      if (!getIftarTime()
          .equals(other.getIftarTime())) return false;
    }
    if (hasScreenSaverOnTime() != other.hasScreenSaverOnTime()) return false;
    if (hasScreenSaverOnTime()) {
      if (!getScreenSaverOnTime()
          .equals(other.getScreenSaverOnTime())) return false;
    }
    if (hasScreenSaverOffTime() != other.hasScreenSaverOffTime()) return false;
    if (hasScreenSaverOffTime()) {
      if (!getScreenSaverOffTime()
          .equals(other.getScreenSaverOffTime())) return false;
    }
    if (getHijriAdjustment()
        != other.getHijriAdjustment()) return false;
    if (getHijriDate()
        != other.getHijriDate()) return false;
    if (!getHijriMonth()
        .equals(other.getHijriMonth())) return false;
    if (getHijriYear()
        != other.getHijriYear()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @SuppressWarnings("unchecked")
@java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasFajrTime()) {
      hash = (37 * hash) + FAJRTIME_FIELD_NUMBER;
      hash = (53 * hash) + getFajrTime().hashCode();
    }
    if (hasZuhrTime()) {
      hash = (37 * hash) + ZUHRTIME_FIELD_NUMBER;
      hash = (53 * hash) + getZuhrTime().hashCode();
    }
    if (hasAsrTime()) {
      hash = (37 * hash) + ASRTIME_FIELD_NUMBER;
      hash = (53 * hash) + getAsrTime().hashCode();
    }
    if (hasIshaTime()) {
      hash = (37 * hash) + ISHATIME_FIELD_NUMBER;
      hash = (53 * hash) + getIshaTime().hashCode();
    }
    if (hasJumuaTime()) {
      hash = (37 * hash) + JUMUATIME_FIELD_NUMBER;
      hash = (53 * hash) + getJumuaTime().hashCode();
    }
    if (hasIshraqTime()) {
      hash = (37 * hash) + ISHRAQTIME_FIELD_NUMBER;
      hash = (53 * hash) + getIshraqTime().hashCode();
    }
    if (hasDuhaTime()) {
      hash = (37 * hash) + DUHATIME_FIELD_NUMBER;
      hash = (53 * hash) + getDuhaTime().hashCode();
    }
    if (hasSuhurTime()) {
      hash = (37 * hash) + SUHURTIME_FIELD_NUMBER;
      hash = (53 * hash) + getSuhurTime().hashCode();
    }
    if (hasIftarTime()) {
      hash = (37 * hash) + IFTARTIME_FIELD_NUMBER;
      hash = (53 * hash) + getIftarTime().hashCode();
    }
    if (hasScreenSaverOnTime()) {
      hash = (37 * hash) + SCREENSAVERONTIME_FIELD_NUMBER;
      hash = (53 * hash) + getScreenSaverOnTime().hashCode();
    }
    if (hasScreenSaverOffTime()) {
      hash = (37 * hash) + SCREENSAVEROFFTIME_FIELD_NUMBER;
      hash = (53 * hash) + getScreenSaverOffTime().hashCode();
    }
    hash = (37 * hash) + HIJRIADJUSTMENT_FIELD_NUMBER;
    hash = (53 * hash) + getHijriAdjustment();
    hash = (37 * hash) + HIJRIDATE_FIELD_NUMBER;
    hash = (53 * hash) + getHijriDate();
    hash = (37 * hash) + HIJRIMONTH_FIELD_NUMBER;
    hash = (53 * hash) + getHijriMonth().hashCode();
    hash = (37 * hash) + HIJRIYEAR_FIELD_NUMBER;
    hash = (53 * hash) + getHijriYear();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest)
      com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mujeeb.mosquedashboard.grpc.MosqueDashboardProto.internal_static_com_mujeeb_mosquedashboard_grpc_GetDataForMobileAppRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mujeeb.mosquedashboard.grpc.MosqueDashboardProto.internal_static_com_mujeeb_mosquedashboard_grpc_GetDataForMobileAppRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest.class, com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest.Builder.class);
    }

    // Construct using com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (fajrTimeBuilder_ == null) {
        fajrTime_ = null;
      } else {
        fajrTime_ = null;
        fajrTimeBuilder_ = null;
      }
      if (zuhrTimeBuilder_ == null) {
        zuhrTime_ = null;
      } else {
        zuhrTime_ = null;
        zuhrTimeBuilder_ = null;
      }
      if (asrTimeBuilder_ == null) {
        asrTime_ = null;
      } else {
        asrTime_ = null;
        asrTimeBuilder_ = null;
      }
      if (ishaTimeBuilder_ == null) {
        ishaTime_ = null;
      } else {
        ishaTime_ = null;
        ishaTimeBuilder_ = null;
      }
      if (jumuaTimeBuilder_ == null) {
        jumuaTime_ = null;
      } else {
        jumuaTime_ = null;
        jumuaTimeBuilder_ = null;
      }
      if (ishraqTimeBuilder_ == null) {
        ishraqTime_ = null;
      } else {
        ishraqTime_ = null;
        ishraqTimeBuilder_ = null;
      }
      if (duhaTimeBuilder_ == null) {
        duhaTime_ = null;
      } else {
        duhaTime_ = null;
        duhaTimeBuilder_ = null;
      }
      if (suhurTimeBuilder_ == null) {
        suhurTime_ = null;
      } else {
        suhurTime_ = null;
        suhurTimeBuilder_ = null;
      }
      if (iftarTimeBuilder_ == null) {
        iftarTime_ = null;
      } else {
        iftarTime_ = null;
        iftarTimeBuilder_ = null;
      }
      if (screenSaverOnTimeBuilder_ == null) {
        screenSaverOnTime_ = null;
      } else {
        screenSaverOnTime_ = null;
        screenSaverOnTimeBuilder_ = null;
      }
      if (screenSaverOffTimeBuilder_ == null) {
        screenSaverOffTime_ = null;
      } else {
        screenSaverOffTime_ = null;
        screenSaverOffTimeBuilder_ = null;
      }
      hijriAdjustment_ = 0;

      hijriDate_ = 0;

      hijriMonth_ = "";

      hijriYear_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mujeeb.mosquedashboard.grpc.MosqueDashboardProto.internal_static_com_mujeeb_mosquedashboard_grpc_GetDataForMobileAppRequest_descriptor;
    }

    @java.lang.Override
    public com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest getDefaultInstanceForType() {
      return com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest build() {
      com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest buildPartial() {
      com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest result = new com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest(this);
      if (fajrTimeBuilder_ == null) {
        result.fajrTime_ = fajrTime_;
      } else {
        result.fajrTime_ = fajrTimeBuilder_.build();
      }
      if (zuhrTimeBuilder_ == null) {
        result.zuhrTime_ = zuhrTime_;
      } else {
        result.zuhrTime_ = zuhrTimeBuilder_.build();
      }
      if (asrTimeBuilder_ == null) {
        result.asrTime_ = asrTime_;
      } else {
        result.asrTime_ = asrTimeBuilder_.build();
      }
      if (ishaTimeBuilder_ == null) {
        result.ishaTime_ = ishaTime_;
      } else {
        result.ishaTime_ = ishaTimeBuilder_.build();
      }
      if (jumuaTimeBuilder_ == null) {
        result.jumuaTime_ = jumuaTime_;
      } else {
        result.jumuaTime_ = jumuaTimeBuilder_.build();
      }
      if (ishraqTimeBuilder_ == null) {
        result.ishraqTime_ = ishraqTime_;
      } else {
        result.ishraqTime_ = ishraqTimeBuilder_.build();
      }
      if (duhaTimeBuilder_ == null) {
        result.duhaTime_ = duhaTime_;
      } else {
        result.duhaTime_ = duhaTimeBuilder_.build();
      }
      if (suhurTimeBuilder_ == null) {
        result.suhurTime_ = suhurTime_;
      } else {
        result.suhurTime_ = suhurTimeBuilder_.build();
      }
      if (iftarTimeBuilder_ == null) {
        result.iftarTime_ = iftarTime_;
      } else {
        result.iftarTime_ = iftarTimeBuilder_.build();
      }
      if (screenSaverOnTimeBuilder_ == null) {
        result.screenSaverOnTime_ = screenSaverOnTime_;
      } else {
        result.screenSaverOnTime_ = screenSaverOnTimeBuilder_.build();
      }
      if (screenSaverOffTimeBuilder_ == null) {
        result.screenSaverOffTime_ = screenSaverOffTime_;
      } else {
        result.screenSaverOffTime_ = screenSaverOffTimeBuilder_.build();
      }
      result.hijriAdjustment_ = hijriAdjustment_;
      result.hijriDate_ = hijriDate_;
      result.hijriMonth_ = hijriMonth_;
      result.hijriYear_ = hijriYear_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest) {
        return mergeFrom((com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest other) {
      if (other == com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest.getDefaultInstance()) return this;
      if (other.hasFajrTime()) {
        mergeFajrTime(other.getFajrTime());
      }
      if (other.hasZuhrTime()) {
        mergeZuhrTime(other.getZuhrTime());
      }
      if (other.hasAsrTime()) {
        mergeAsrTime(other.getAsrTime());
      }
      if (other.hasIshaTime()) {
        mergeIshaTime(other.getIshaTime());
      }
      if (other.hasJumuaTime()) {
        mergeJumuaTime(other.getJumuaTime());
      }
      if (other.hasIshraqTime()) {
        mergeIshraqTime(other.getIshraqTime());
      }
      if (other.hasDuhaTime()) {
        mergeDuhaTime(other.getDuhaTime());
      }
      if (other.hasSuhurTime()) {
        mergeSuhurTime(other.getSuhurTime());
      }
      if (other.hasIftarTime()) {
        mergeIftarTime(other.getIftarTime());
      }
      if (other.hasScreenSaverOnTime()) {
        mergeScreenSaverOnTime(other.getScreenSaverOnTime());
      }
      if (other.hasScreenSaverOffTime()) {
        mergeScreenSaverOffTime(other.getScreenSaverOffTime());
      }
      if (other.getHijriAdjustment() != 0) {
        setHijriAdjustment(other.getHijriAdjustment());
      }
      if (other.getHijriDate() != 0) {
        setHijriDate(other.getHijriDate());
      }
      if (!other.getHijriMonth().isEmpty()) {
        hijriMonth_ = other.hijriMonth_;
        onChanged();
      }
      if (other.getHijriYear() != 0) {
        setHijriYear(other.getHijriYear());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.mujeeb.mosquedashboard.grpc.NamazTime fajrTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mujeeb.mosquedashboard.grpc.NamazTime, com.mujeeb.mosquedashboard.grpc.NamazTime.Builder, com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder> fajrTimeBuilder_;
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime fajrTime = 1;</code>
     * @return Whether the fajrTime field is set.
     */
    public boolean hasFajrTime() {
      return fajrTimeBuilder_ != null || fajrTime_ != null;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime fajrTime = 1;</code>
     * @return The fajrTime.
     */
    public com.mujeeb.mosquedashboard.grpc.NamazTime getFajrTime() {
      if (fajrTimeBuilder_ == null) {
        return fajrTime_ == null ? com.mujeeb.mosquedashboard.grpc.NamazTime.getDefaultInstance() : fajrTime_;
      } else {
        return fajrTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime fajrTime = 1;</code>
     */
    public Builder setFajrTime(com.mujeeb.mosquedashboard.grpc.NamazTime value) {
      if (fajrTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        fajrTime_ = value;
        onChanged();
      } else {
        fajrTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime fajrTime = 1;</code>
     */
    public Builder setFajrTime(
        com.mujeeb.mosquedashboard.grpc.NamazTime.Builder builderForValue) {
      if (fajrTimeBuilder_ == null) {
        fajrTime_ = builderForValue.build();
        onChanged();
      } else {
        fajrTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime fajrTime = 1;</code>
     */
    public Builder mergeFajrTime(com.mujeeb.mosquedashboard.grpc.NamazTime value) {
      if (fajrTimeBuilder_ == null) {
        if (fajrTime_ != null) {
          fajrTime_ =
            com.mujeeb.mosquedashboard.grpc.NamazTime.newBuilder(fajrTime_).mergeFrom(value).buildPartial();
        } else {
          fajrTime_ = value;
        }
        onChanged();
      } else {
        fajrTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime fajrTime = 1;</code>
     */
    public Builder clearFajrTime() {
      if (fajrTimeBuilder_ == null) {
        fajrTime_ = null;
        onChanged();
      } else {
        fajrTime_ = null;
        fajrTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime fajrTime = 1;</code>
     */
    public com.mujeeb.mosquedashboard.grpc.NamazTime.Builder getFajrTimeBuilder() {
      
      onChanged();
      return getFajrTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime fajrTime = 1;</code>
     */
    public com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder getFajrTimeOrBuilder() {
      if (fajrTimeBuilder_ != null) {
        return fajrTimeBuilder_.getMessageOrBuilder();
      } else {
        return fajrTime_ == null ?
            com.mujeeb.mosquedashboard.grpc.NamazTime.getDefaultInstance() : fajrTime_;
      }
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime fajrTime = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mujeeb.mosquedashboard.grpc.NamazTime, com.mujeeb.mosquedashboard.grpc.NamazTime.Builder, com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder> 
        getFajrTimeFieldBuilder() {
      if (fajrTimeBuilder_ == null) {
        fajrTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.mujeeb.mosquedashboard.grpc.NamazTime, com.mujeeb.mosquedashboard.grpc.NamazTime.Builder, com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder>(
                getFajrTime(),
                getParentForChildren(),
                isClean());
        fajrTime_ = null;
      }
      return fajrTimeBuilder_;
    }

    private com.mujeeb.mosquedashboard.grpc.NamazTime zuhrTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mujeeb.mosquedashboard.grpc.NamazTime, com.mujeeb.mosquedashboard.grpc.NamazTime.Builder, com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder> zuhrTimeBuilder_;
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime zuhrTime = 2;</code>
     * @return Whether the zuhrTime field is set.
     */
    public boolean hasZuhrTime() {
      return zuhrTimeBuilder_ != null || zuhrTime_ != null;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime zuhrTime = 2;</code>
     * @return The zuhrTime.
     */
    public com.mujeeb.mosquedashboard.grpc.NamazTime getZuhrTime() {
      if (zuhrTimeBuilder_ == null) {
        return zuhrTime_ == null ? com.mujeeb.mosquedashboard.grpc.NamazTime.getDefaultInstance() : zuhrTime_;
      } else {
        return zuhrTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime zuhrTime = 2;</code>
     */
    public Builder setZuhrTime(com.mujeeb.mosquedashboard.grpc.NamazTime value) {
      if (zuhrTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        zuhrTime_ = value;
        onChanged();
      } else {
        zuhrTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime zuhrTime = 2;</code>
     */
    public Builder setZuhrTime(
        com.mujeeb.mosquedashboard.grpc.NamazTime.Builder builderForValue) {
      if (zuhrTimeBuilder_ == null) {
        zuhrTime_ = builderForValue.build();
        onChanged();
      } else {
        zuhrTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime zuhrTime = 2;</code>
     */
    public Builder mergeZuhrTime(com.mujeeb.mosquedashboard.grpc.NamazTime value) {
      if (zuhrTimeBuilder_ == null) {
        if (zuhrTime_ != null) {
          zuhrTime_ =
            com.mujeeb.mosquedashboard.grpc.NamazTime.newBuilder(zuhrTime_).mergeFrom(value).buildPartial();
        } else {
          zuhrTime_ = value;
        }
        onChanged();
      } else {
        zuhrTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime zuhrTime = 2;</code>
     */
    public Builder clearZuhrTime() {
      if (zuhrTimeBuilder_ == null) {
        zuhrTime_ = null;
        onChanged();
      } else {
        zuhrTime_ = null;
        zuhrTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime zuhrTime = 2;</code>
     */
    public com.mujeeb.mosquedashboard.grpc.NamazTime.Builder getZuhrTimeBuilder() {
      
      onChanged();
      return getZuhrTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime zuhrTime = 2;</code>
     */
    public com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder getZuhrTimeOrBuilder() {
      if (zuhrTimeBuilder_ != null) {
        return zuhrTimeBuilder_.getMessageOrBuilder();
      } else {
        return zuhrTime_ == null ?
            com.mujeeb.mosquedashboard.grpc.NamazTime.getDefaultInstance() : zuhrTime_;
      }
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime zuhrTime = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mujeeb.mosquedashboard.grpc.NamazTime, com.mujeeb.mosquedashboard.grpc.NamazTime.Builder, com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder> 
        getZuhrTimeFieldBuilder() {
      if (zuhrTimeBuilder_ == null) {
        zuhrTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.mujeeb.mosquedashboard.grpc.NamazTime, com.mujeeb.mosquedashboard.grpc.NamazTime.Builder, com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder>(
                getZuhrTime(),
                getParentForChildren(),
                isClean());
        zuhrTime_ = null;
      }
      return zuhrTimeBuilder_;
    }

    private com.mujeeb.mosquedashboard.grpc.NamazTime asrTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mujeeb.mosquedashboard.grpc.NamazTime, com.mujeeb.mosquedashboard.grpc.NamazTime.Builder, com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder> asrTimeBuilder_;
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime asrTime = 3;</code>
     * @return Whether the asrTime field is set.
     */
    public boolean hasAsrTime() {
      return asrTimeBuilder_ != null || asrTime_ != null;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime asrTime = 3;</code>
     * @return The asrTime.
     */
    public com.mujeeb.mosquedashboard.grpc.NamazTime getAsrTime() {
      if (asrTimeBuilder_ == null) {
        return asrTime_ == null ? com.mujeeb.mosquedashboard.grpc.NamazTime.getDefaultInstance() : asrTime_;
      } else {
        return asrTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime asrTime = 3;</code>
     */
    public Builder setAsrTime(com.mujeeb.mosquedashboard.grpc.NamazTime value) {
      if (asrTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        asrTime_ = value;
        onChanged();
      } else {
        asrTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime asrTime = 3;</code>
     */
    public Builder setAsrTime(
        com.mujeeb.mosquedashboard.grpc.NamazTime.Builder builderForValue) {
      if (asrTimeBuilder_ == null) {
        asrTime_ = builderForValue.build();
        onChanged();
      } else {
        asrTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime asrTime = 3;</code>
     */
    public Builder mergeAsrTime(com.mujeeb.mosquedashboard.grpc.NamazTime value) {
      if (asrTimeBuilder_ == null) {
        if (asrTime_ != null) {
          asrTime_ =
            com.mujeeb.mosquedashboard.grpc.NamazTime.newBuilder(asrTime_).mergeFrom(value).buildPartial();
        } else {
          asrTime_ = value;
        }
        onChanged();
      } else {
        asrTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime asrTime = 3;</code>
     */
    public Builder clearAsrTime() {
      if (asrTimeBuilder_ == null) {
        asrTime_ = null;
        onChanged();
      } else {
        asrTime_ = null;
        asrTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime asrTime = 3;</code>
     */
    public com.mujeeb.mosquedashboard.grpc.NamazTime.Builder getAsrTimeBuilder() {
      
      onChanged();
      return getAsrTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime asrTime = 3;</code>
     */
    public com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder getAsrTimeOrBuilder() {
      if (asrTimeBuilder_ != null) {
        return asrTimeBuilder_.getMessageOrBuilder();
      } else {
        return asrTime_ == null ?
            com.mujeeb.mosquedashboard.grpc.NamazTime.getDefaultInstance() : asrTime_;
      }
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime asrTime = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mujeeb.mosquedashboard.grpc.NamazTime, com.mujeeb.mosquedashboard.grpc.NamazTime.Builder, com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder> 
        getAsrTimeFieldBuilder() {
      if (asrTimeBuilder_ == null) {
        asrTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.mujeeb.mosquedashboard.grpc.NamazTime, com.mujeeb.mosquedashboard.grpc.NamazTime.Builder, com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder>(
                getAsrTime(),
                getParentForChildren(),
                isClean());
        asrTime_ = null;
      }
      return asrTimeBuilder_;
    }

    private com.mujeeb.mosquedashboard.grpc.NamazTime ishaTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mujeeb.mosquedashboard.grpc.NamazTime, com.mujeeb.mosquedashboard.grpc.NamazTime.Builder, com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder> ishaTimeBuilder_;
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime ishaTime = 4;</code>
     * @return Whether the ishaTime field is set.
     */
    public boolean hasIshaTime() {
      return ishaTimeBuilder_ != null || ishaTime_ != null;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime ishaTime = 4;</code>
     * @return The ishaTime.
     */
    public com.mujeeb.mosquedashboard.grpc.NamazTime getIshaTime() {
      if (ishaTimeBuilder_ == null) {
        return ishaTime_ == null ? com.mujeeb.mosquedashboard.grpc.NamazTime.getDefaultInstance() : ishaTime_;
      } else {
        return ishaTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime ishaTime = 4;</code>
     */
    public Builder setIshaTime(com.mujeeb.mosquedashboard.grpc.NamazTime value) {
      if (ishaTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ishaTime_ = value;
        onChanged();
      } else {
        ishaTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime ishaTime = 4;</code>
     */
    public Builder setIshaTime(
        com.mujeeb.mosquedashboard.grpc.NamazTime.Builder builderForValue) {
      if (ishaTimeBuilder_ == null) {
        ishaTime_ = builderForValue.build();
        onChanged();
      } else {
        ishaTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime ishaTime = 4;</code>
     */
    public Builder mergeIshaTime(com.mujeeb.mosquedashboard.grpc.NamazTime value) {
      if (ishaTimeBuilder_ == null) {
        if (ishaTime_ != null) {
          ishaTime_ =
            com.mujeeb.mosquedashboard.grpc.NamazTime.newBuilder(ishaTime_).mergeFrom(value).buildPartial();
        } else {
          ishaTime_ = value;
        }
        onChanged();
      } else {
        ishaTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime ishaTime = 4;</code>
     */
    public Builder clearIshaTime() {
      if (ishaTimeBuilder_ == null) {
        ishaTime_ = null;
        onChanged();
      } else {
        ishaTime_ = null;
        ishaTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime ishaTime = 4;</code>
     */
    public com.mujeeb.mosquedashboard.grpc.NamazTime.Builder getIshaTimeBuilder() {
      
      onChanged();
      return getIshaTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime ishaTime = 4;</code>
     */
    public com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder getIshaTimeOrBuilder() {
      if (ishaTimeBuilder_ != null) {
        return ishaTimeBuilder_.getMessageOrBuilder();
      } else {
        return ishaTime_ == null ?
            com.mujeeb.mosquedashboard.grpc.NamazTime.getDefaultInstance() : ishaTime_;
      }
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime ishaTime = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mujeeb.mosquedashboard.grpc.NamazTime, com.mujeeb.mosquedashboard.grpc.NamazTime.Builder, com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder> 
        getIshaTimeFieldBuilder() {
      if (ishaTimeBuilder_ == null) {
        ishaTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.mujeeb.mosquedashboard.grpc.NamazTime, com.mujeeb.mosquedashboard.grpc.NamazTime.Builder, com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder>(
                getIshaTime(),
                getParentForChildren(),
                isClean());
        ishaTime_ = null;
      }
      return ishaTimeBuilder_;
    }

    private com.mujeeb.mosquedashboard.grpc.NamazTime jumuaTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mujeeb.mosquedashboard.grpc.NamazTime, com.mujeeb.mosquedashboard.grpc.NamazTime.Builder, com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder> jumuaTimeBuilder_;
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime jumuaTime = 5;</code>
     * @return Whether the jumuaTime field is set.
     */
    public boolean hasJumuaTime() {
      return jumuaTimeBuilder_ != null || jumuaTime_ != null;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime jumuaTime = 5;</code>
     * @return The jumuaTime.
     */
    public com.mujeeb.mosquedashboard.grpc.NamazTime getJumuaTime() {
      if (jumuaTimeBuilder_ == null) {
        return jumuaTime_ == null ? com.mujeeb.mosquedashboard.grpc.NamazTime.getDefaultInstance() : jumuaTime_;
      } else {
        return jumuaTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime jumuaTime = 5;</code>
     */
    public Builder setJumuaTime(com.mujeeb.mosquedashboard.grpc.NamazTime value) {
      if (jumuaTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        jumuaTime_ = value;
        onChanged();
      } else {
        jumuaTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime jumuaTime = 5;</code>
     */
    public Builder setJumuaTime(
        com.mujeeb.mosquedashboard.grpc.NamazTime.Builder builderForValue) {
      if (jumuaTimeBuilder_ == null) {
        jumuaTime_ = builderForValue.build();
        onChanged();
      } else {
        jumuaTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime jumuaTime = 5;</code>
     */
    public Builder mergeJumuaTime(com.mujeeb.mosquedashboard.grpc.NamazTime value) {
      if (jumuaTimeBuilder_ == null) {
        if (jumuaTime_ != null) {
          jumuaTime_ =
            com.mujeeb.mosquedashboard.grpc.NamazTime.newBuilder(jumuaTime_).mergeFrom(value).buildPartial();
        } else {
          jumuaTime_ = value;
        }
        onChanged();
      } else {
        jumuaTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime jumuaTime = 5;</code>
     */
    public Builder clearJumuaTime() {
      if (jumuaTimeBuilder_ == null) {
        jumuaTime_ = null;
        onChanged();
      } else {
        jumuaTime_ = null;
        jumuaTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime jumuaTime = 5;</code>
     */
    public com.mujeeb.mosquedashboard.grpc.NamazTime.Builder getJumuaTimeBuilder() {
      
      onChanged();
      return getJumuaTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime jumuaTime = 5;</code>
     */
    public com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder getJumuaTimeOrBuilder() {
      if (jumuaTimeBuilder_ != null) {
        return jumuaTimeBuilder_.getMessageOrBuilder();
      } else {
        return jumuaTime_ == null ?
            com.mujeeb.mosquedashboard.grpc.NamazTime.getDefaultInstance() : jumuaTime_;
      }
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime jumuaTime = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mujeeb.mosquedashboard.grpc.NamazTime, com.mujeeb.mosquedashboard.grpc.NamazTime.Builder, com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder> 
        getJumuaTimeFieldBuilder() {
      if (jumuaTimeBuilder_ == null) {
        jumuaTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.mujeeb.mosquedashboard.grpc.NamazTime, com.mujeeb.mosquedashboard.grpc.NamazTime.Builder, com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder>(
                getJumuaTime(),
                getParentForChildren(),
                isClean());
        jumuaTime_ = null;
      }
      return jumuaTimeBuilder_;
    }

    private com.mujeeb.mosquedashboard.grpc.NamazTime ishraqTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mujeeb.mosquedashboard.grpc.NamazTime, com.mujeeb.mosquedashboard.grpc.NamazTime.Builder, com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder> ishraqTimeBuilder_;
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime ishraqTime = 6;</code>
     * @return Whether the ishraqTime field is set.
     */
    public boolean hasIshraqTime() {
      return ishraqTimeBuilder_ != null || ishraqTime_ != null;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime ishraqTime = 6;</code>
     * @return The ishraqTime.
     */
    public com.mujeeb.mosquedashboard.grpc.NamazTime getIshraqTime() {
      if (ishraqTimeBuilder_ == null) {
        return ishraqTime_ == null ? com.mujeeb.mosquedashboard.grpc.NamazTime.getDefaultInstance() : ishraqTime_;
      } else {
        return ishraqTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime ishraqTime = 6;</code>
     */
    public Builder setIshraqTime(com.mujeeb.mosquedashboard.grpc.NamazTime value) {
      if (ishraqTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ishraqTime_ = value;
        onChanged();
      } else {
        ishraqTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime ishraqTime = 6;</code>
     */
    public Builder setIshraqTime(
        com.mujeeb.mosquedashboard.grpc.NamazTime.Builder builderForValue) {
      if (ishraqTimeBuilder_ == null) {
        ishraqTime_ = builderForValue.build();
        onChanged();
      } else {
        ishraqTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime ishraqTime = 6;</code>
     */
    public Builder mergeIshraqTime(com.mujeeb.mosquedashboard.grpc.NamazTime value) {
      if (ishraqTimeBuilder_ == null) {
        if (ishraqTime_ != null) {
          ishraqTime_ =
            com.mujeeb.mosquedashboard.grpc.NamazTime.newBuilder(ishraqTime_).mergeFrom(value).buildPartial();
        } else {
          ishraqTime_ = value;
        }
        onChanged();
      } else {
        ishraqTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime ishraqTime = 6;</code>
     */
    public Builder clearIshraqTime() {
      if (ishraqTimeBuilder_ == null) {
        ishraqTime_ = null;
        onChanged();
      } else {
        ishraqTime_ = null;
        ishraqTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime ishraqTime = 6;</code>
     */
    public com.mujeeb.mosquedashboard.grpc.NamazTime.Builder getIshraqTimeBuilder() {
      
      onChanged();
      return getIshraqTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime ishraqTime = 6;</code>
     */
    public com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder getIshraqTimeOrBuilder() {
      if (ishraqTimeBuilder_ != null) {
        return ishraqTimeBuilder_.getMessageOrBuilder();
      } else {
        return ishraqTime_ == null ?
            com.mujeeb.mosquedashboard.grpc.NamazTime.getDefaultInstance() : ishraqTime_;
      }
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime ishraqTime = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mujeeb.mosquedashboard.grpc.NamazTime, com.mujeeb.mosquedashboard.grpc.NamazTime.Builder, com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder> 
        getIshraqTimeFieldBuilder() {
      if (ishraqTimeBuilder_ == null) {
        ishraqTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.mujeeb.mosquedashboard.grpc.NamazTime, com.mujeeb.mosquedashboard.grpc.NamazTime.Builder, com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder>(
                getIshraqTime(),
                getParentForChildren(),
                isClean());
        ishraqTime_ = null;
      }
      return ishraqTimeBuilder_;
    }

    private com.mujeeb.mosquedashboard.grpc.NamazTime duhaTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mujeeb.mosquedashboard.grpc.NamazTime, com.mujeeb.mosquedashboard.grpc.NamazTime.Builder, com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder> duhaTimeBuilder_;
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime duhaTime = 7;</code>
     * @return Whether the duhaTime field is set.
     */
    public boolean hasDuhaTime() {
      return duhaTimeBuilder_ != null || duhaTime_ != null;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime duhaTime = 7;</code>
     * @return The duhaTime.
     */
    public com.mujeeb.mosquedashboard.grpc.NamazTime getDuhaTime() {
      if (duhaTimeBuilder_ == null) {
        return duhaTime_ == null ? com.mujeeb.mosquedashboard.grpc.NamazTime.getDefaultInstance() : duhaTime_;
      } else {
        return duhaTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime duhaTime = 7;</code>
     */
    public Builder setDuhaTime(com.mujeeb.mosquedashboard.grpc.NamazTime value) {
      if (duhaTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        duhaTime_ = value;
        onChanged();
      } else {
        duhaTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime duhaTime = 7;</code>
     */
    public Builder setDuhaTime(
        com.mujeeb.mosquedashboard.grpc.NamazTime.Builder builderForValue) {
      if (duhaTimeBuilder_ == null) {
        duhaTime_ = builderForValue.build();
        onChanged();
      } else {
        duhaTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime duhaTime = 7;</code>
     */
    public Builder mergeDuhaTime(com.mujeeb.mosquedashboard.grpc.NamazTime value) {
      if (duhaTimeBuilder_ == null) {
        if (duhaTime_ != null) {
          duhaTime_ =
            com.mujeeb.mosquedashboard.grpc.NamazTime.newBuilder(duhaTime_).mergeFrom(value).buildPartial();
        } else {
          duhaTime_ = value;
        }
        onChanged();
      } else {
        duhaTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime duhaTime = 7;</code>
     */
    public Builder clearDuhaTime() {
      if (duhaTimeBuilder_ == null) {
        duhaTime_ = null;
        onChanged();
      } else {
        duhaTime_ = null;
        duhaTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime duhaTime = 7;</code>
     */
    public com.mujeeb.mosquedashboard.grpc.NamazTime.Builder getDuhaTimeBuilder() {
      
      onChanged();
      return getDuhaTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime duhaTime = 7;</code>
     */
    public com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder getDuhaTimeOrBuilder() {
      if (duhaTimeBuilder_ != null) {
        return duhaTimeBuilder_.getMessageOrBuilder();
      } else {
        return duhaTime_ == null ?
            com.mujeeb.mosquedashboard.grpc.NamazTime.getDefaultInstance() : duhaTime_;
      }
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime duhaTime = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mujeeb.mosquedashboard.grpc.NamazTime, com.mujeeb.mosquedashboard.grpc.NamazTime.Builder, com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder> 
        getDuhaTimeFieldBuilder() {
      if (duhaTimeBuilder_ == null) {
        duhaTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.mujeeb.mosquedashboard.grpc.NamazTime, com.mujeeb.mosquedashboard.grpc.NamazTime.Builder, com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder>(
                getDuhaTime(),
                getParentForChildren(),
                isClean());
        duhaTime_ = null;
      }
      return duhaTimeBuilder_;
    }

    private com.mujeeb.mosquedashboard.grpc.NamazTime suhurTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mujeeb.mosquedashboard.grpc.NamazTime, com.mujeeb.mosquedashboard.grpc.NamazTime.Builder, com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder> suhurTimeBuilder_;
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime suhurTime = 8;</code>
     * @return Whether the suhurTime field is set.
     */
    public boolean hasSuhurTime() {
      return suhurTimeBuilder_ != null || suhurTime_ != null;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime suhurTime = 8;</code>
     * @return The suhurTime.
     */
    public com.mujeeb.mosquedashboard.grpc.NamazTime getSuhurTime() {
      if (suhurTimeBuilder_ == null) {
        return suhurTime_ == null ? com.mujeeb.mosquedashboard.grpc.NamazTime.getDefaultInstance() : suhurTime_;
      } else {
        return suhurTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime suhurTime = 8;</code>
     */
    public Builder setSuhurTime(com.mujeeb.mosquedashboard.grpc.NamazTime value) {
      if (suhurTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        suhurTime_ = value;
        onChanged();
      } else {
        suhurTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime suhurTime = 8;</code>
     */
    public Builder setSuhurTime(
        com.mujeeb.mosquedashboard.grpc.NamazTime.Builder builderForValue) {
      if (suhurTimeBuilder_ == null) {
        suhurTime_ = builderForValue.build();
        onChanged();
      } else {
        suhurTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime suhurTime = 8;</code>
     */
    public Builder mergeSuhurTime(com.mujeeb.mosquedashboard.grpc.NamazTime value) {
      if (suhurTimeBuilder_ == null) {
        if (suhurTime_ != null) {
          suhurTime_ =
            com.mujeeb.mosquedashboard.grpc.NamazTime.newBuilder(suhurTime_).mergeFrom(value).buildPartial();
        } else {
          suhurTime_ = value;
        }
        onChanged();
      } else {
        suhurTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime suhurTime = 8;</code>
     */
    public Builder clearSuhurTime() {
      if (suhurTimeBuilder_ == null) {
        suhurTime_ = null;
        onChanged();
      } else {
        suhurTime_ = null;
        suhurTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime suhurTime = 8;</code>
     */
    public com.mujeeb.mosquedashboard.grpc.NamazTime.Builder getSuhurTimeBuilder() {
      
      onChanged();
      return getSuhurTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime suhurTime = 8;</code>
     */
    public com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder getSuhurTimeOrBuilder() {
      if (suhurTimeBuilder_ != null) {
        return suhurTimeBuilder_.getMessageOrBuilder();
      } else {
        return suhurTime_ == null ?
            com.mujeeb.mosquedashboard.grpc.NamazTime.getDefaultInstance() : suhurTime_;
      }
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime suhurTime = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mujeeb.mosquedashboard.grpc.NamazTime, com.mujeeb.mosquedashboard.grpc.NamazTime.Builder, com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder> 
        getSuhurTimeFieldBuilder() {
      if (suhurTimeBuilder_ == null) {
        suhurTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.mujeeb.mosquedashboard.grpc.NamazTime, com.mujeeb.mosquedashboard.grpc.NamazTime.Builder, com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder>(
                getSuhurTime(),
                getParentForChildren(),
                isClean());
        suhurTime_ = null;
      }
      return suhurTimeBuilder_;
    }

    private com.mujeeb.mosquedashboard.grpc.NamazTime iftarTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mujeeb.mosquedashboard.grpc.NamazTime, com.mujeeb.mosquedashboard.grpc.NamazTime.Builder, com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder> iftarTimeBuilder_;
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime iftarTime = 9;</code>
     * @return Whether the iftarTime field is set.
     */
    public boolean hasIftarTime() {
      return iftarTimeBuilder_ != null || iftarTime_ != null;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime iftarTime = 9;</code>
     * @return The iftarTime.
     */
    public com.mujeeb.mosquedashboard.grpc.NamazTime getIftarTime() {
      if (iftarTimeBuilder_ == null) {
        return iftarTime_ == null ? com.mujeeb.mosquedashboard.grpc.NamazTime.getDefaultInstance() : iftarTime_;
      } else {
        return iftarTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime iftarTime = 9;</code>
     */
    public Builder setIftarTime(com.mujeeb.mosquedashboard.grpc.NamazTime value) {
      if (iftarTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        iftarTime_ = value;
        onChanged();
      } else {
        iftarTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime iftarTime = 9;</code>
     */
    public Builder setIftarTime(
        com.mujeeb.mosquedashboard.grpc.NamazTime.Builder builderForValue) {
      if (iftarTimeBuilder_ == null) {
        iftarTime_ = builderForValue.build();
        onChanged();
      } else {
        iftarTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime iftarTime = 9;</code>
     */
    public Builder mergeIftarTime(com.mujeeb.mosquedashboard.grpc.NamazTime value) {
      if (iftarTimeBuilder_ == null) {
        if (iftarTime_ != null) {
          iftarTime_ =
            com.mujeeb.mosquedashboard.grpc.NamazTime.newBuilder(iftarTime_).mergeFrom(value).buildPartial();
        } else {
          iftarTime_ = value;
        }
        onChanged();
      } else {
        iftarTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime iftarTime = 9;</code>
     */
    public Builder clearIftarTime() {
      if (iftarTimeBuilder_ == null) {
        iftarTime_ = null;
        onChanged();
      } else {
        iftarTime_ = null;
        iftarTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime iftarTime = 9;</code>
     */
    public com.mujeeb.mosquedashboard.grpc.NamazTime.Builder getIftarTimeBuilder() {
      
      onChanged();
      return getIftarTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime iftarTime = 9;</code>
     */
    public com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder getIftarTimeOrBuilder() {
      if (iftarTimeBuilder_ != null) {
        return iftarTimeBuilder_.getMessageOrBuilder();
      } else {
        return iftarTime_ == null ?
            com.mujeeb.mosquedashboard.grpc.NamazTime.getDefaultInstance() : iftarTime_;
      }
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime iftarTime = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mujeeb.mosquedashboard.grpc.NamazTime, com.mujeeb.mosquedashboard.grpc.NamazTime.Builder, com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder> 
        getIftarTimeFieldBuilder() {
      if (iftarTimeBuilder_ == null) {
        iftarTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.mujeeb.mosquedashboard.grpc.NamazTime, com.mujeeb.mosquedashboard.grpc.NamazTime.Builder, com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder>(
                getIftarTime(),
                getParentForChildren(),
                isClean());
        iftarTime_ = null;
      }
      return iftarTimeBuilder_;
    }

    private com.mujeeb.mosquedashboard.grpc.NamazTime screenSaverOnTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mujeeb.mosquedashboard.grpc.NamazTime, com.mujeeb.mosquedashboard.grpc.NamazTime.Builder, com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder> screenSaverOnTimeBuilder_;
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime screenSaverOnTime = 10;</code>
     * @return Whether the screenSaverOnTime field is set.
     */
    public boolean hasScreenSaverOnTime() {
      return screenSaverOnTimeBuilder_ != null || screenSaverOnTime_ != null;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime screenSaverOnTime = 10;</code>
     * @return The screenSaverOnTime.
     */
    public com.mujeeb.mosquedashboard.grpc.NamazTime getScreenSaverOnTime() {
      if (screenSaverOnTimeBuilder_ == null) {
        return screenSaverOnTime_ == null ? com.mujeeb.mosquedashboard.grpc.NamazTime.getDefaultInstance() : screenSaverOnTime_;
      } else {
        return screenSaverOnTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime screenSaverOnTime = 10;</code>
     */
    public Builder setScreenSaverOnTime(com.mujeeb.mosquedashboard.grpc.NamazTime value) {
      if (screenSaverOnTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        screenSaverOnTime_ = value;
        onChanged();
      } else {
        screenSaverOnTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime screenSaverOnTime = 10;</code>
     */
    public Builder setScreenSaverOnTime(
        com.mujeeb.mosquedashboard.grpc.NamazTime.Builder builderForValue) {
      if (screenSaverOnTimeBuilder_ == null) {
        screenSaverOnTime_ = builderForValue.build();
        onChanged();
      } else {
        screenSaverOnTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime screenSaverOnTime = 10;</code>
     */
    public Builder mergeScreenSaverOnTime(com.mujeeb.mosquedashboard.grpc.NamazTime value) {
      if (screenSaverOnTimeBuilder_ == null) {
        if (screenSaverOnTime_ != null) {
          screenSaverOnTime_ =
            com.mujeeb.mosquedashboard.grpc.NamazTime.newBuilder(screenSaverOnTime_).mergeFrom(value).buildPartial();
        } else {
          screenSaverOnTime_ = value;
        }
        onChanged();
      } else {
        screenSaverOnTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime screenSaverOnTime = 10;</code>
     */
    public Builder clearScreenSaverOnTime() {
      if (screenSaverOnTimeBuilder_ == null) {
        screenSaverOnTime_ = null;
        onChanged();
      } else {
        screenSaverOnTime_ = null;
        screenSaverOnTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime screenSaverOnTime = 10;</code>
     */
    public com.mujeeb.mosquedashboard.grpc.NamazTime.Builder getScreenSaverOnTimeBuilder() {
      
      onChanged();
      return getScreenSaverOnTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime screenSaverOnTime = 10;</code>
     */
    public com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder getScreenSaverOnTimeOrBuilder() {
      if (screenSaverOnTimeBuilder_ != null) {
        return screenSaverOnTimeBuilder_.getMessageOrBuilder();
      } else {
        return screenSaverOnTime_ == null ?
            com.mujeeb.mosquedashboard.grpc.NamazTime.getDefaultInstance() : screenSaverOnTime_;
      }
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime screenSaverOnTime = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mujeeb.mosquedashboard.grpc.NamazTime, com.mujeeb.mosquedashboard.grpc.NamazTime.Builder, com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder> 
        getScreenSaverOnTimeFieldBuilder() {
      if (screenSaverOnTimeBuilder_ == null) {
        screenSaverOnTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.mujeeb.mosquedashboard.grpc.NamazTime, com.mujeeb.mosquedashboard.grpc.NamazTime.Builder, com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder>(
                getScreenSaverOnTime(),
                getParentForChildren(),
                isClean());
        screenSaverOnTime_ = null;
      }
      return screenSaverOnTimeBuilder_;
    }

    private com.mujeeb.mosquedashboard.grpc.NamazTime screenSaverOffTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mujeeb.mosquedashboard.grpc.NamazTime, com.mujeeb.mosquedashboard.grpc.NamazTime.Builder, com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder> screenSaverOffTimeBuilder_;
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime screenSaverOffTime = 11;</code>
     * @return Whether the screenSaverOffTime field is set.
     */
    public boolean hasScreenSaverOffTime() {
      return screenSaverOffTimeBuilder_ != null || screenSaverOffTime_ != null;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime screenSaverOffTime = 11;</code>
     * @return The screenSaverOffTime.
     */
    public com.mujeeb.mosquedashboard.grpc.NamazTime getScreenSaverOffTime() {
      if (screenSaverOffTimeBuilder_ == null) {
        return screenSaverOffTime_ == null ? com.mujeeb.mosquedashboard.grpc.NamazTime.getDefaultInstance() : screenSaverOffTime_;
      } else {
        return screenSaverOffTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime screenSaverOffTime = 11;</code>
     */
    public Builder setScreenSaverOffTime(com.mujeeb.mosquedashboard.grpc.NamazTime value) {
      if (screenSaverOffTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        screenSaverOffTime_ = value;
        onChanged();
      } else {
        screenSaverOffTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime screenSaverOffTime = 11;</code>
     */
    public Builder setScreenSaverOffTime(
        com.mujeeb.mosquedashboard.grpc.NamazTime.Builder builderForValue) {
      if (screenSaverOffTimeBuilder_ == null) {
        screenSaverOffTime_ = builderForValue.build();
        onChanged();
      } else {
        screenSaverOffTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime screenSaverOffTime = 11;</code>
     */
    public Builder mergeScreenSaverOffTime(com.mujeeb.mosquedashboard.grpc.NamazTime value) {
      if (screenSaverOffTimeBuilder_ == null) {
        if (screenSaverOffTime_ != null) {
          screenSaverOffTime_ =
            com.mujeeb.mosquedashboard.grpc.NamazTime.newBuilder(screenSaverOffTime_).mergeFrom(value).buildPartial();
        } else {
          screenSaverOffTime_ = value;
        }
        onChanged();
      } else {
        screenSaverOffTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime screenSaverOffTime = 11;</code>
     */
    public Builder clearScreenSaverOffTime() {
      if (screenSaverOffTimeBuilder_ == null) {
        screenSaverOffTime_ = null;
        onChanged();
      } else {
        screenSaverOffTime_ = null;
        screenSaverOffTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime screenSaverOffTime = 11;</code>
     */
    public com.mujeeb.mosquedashboard.grpc.NamazTime.Builder getScreenSaverOffTimeBuilder() {
      
      onChanged();
      return getScreenSaverOffTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime screenSaverOffTime = 11;</code>
     */
    public com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder getScreenSaverOffTimeOrBuilder() {
      if (screenSaverOffTimeBuilder_ != null) {
        return screenSaverOffTimeBuilder_.getMessageOrBuilder();
      } else {
        return screenSaverOffTime_ == null ?
            com.mujeeb.mosquedashboard.grpc.NamazTime.getDefaultInstance() : screenSaverOffTime_;
      }
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime screenSaverOffTime = 11;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mujeeb.mosquedashboard.grpc.NamazTime, com.mujeeb.mosquedashboard.grpc.NamazTime.Builder, com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder> 
        getScreenSaverOffTimeFieldBuilder() {
      if (screenSaverOffTimeBuilder_ == null) {
        screenSaverOffTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.mujeeb.mosquedashboard.grpc.NamazTime, com.mujeeb.mosquedashboard.grpc.NamazTime.Builder, com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder>(
                getScreenSaverOffTime(),
                getParentForChildren(),
                isClean());
        screenSaverOffTime_ = null;
      }
      return screenSaverOffTimeBuilder_;
    }

    private int hijriAdjustment_ ;
    /**
     * <code>int32 hijriAdjustment = 12;</code>
     * @return The hijriAdjustment.
     */
    @java.lang.Override
    public int getHijriAdjustment() {
      return hijriAdjustment_;
    }
    /**
     * <code>int32 hijriAdjustment = 12;</code>
     * @param value The hijriAdjustment to set.
     * @return This builder for chaining.
     */
    public Builder setHijriAdjustment(int value) {
      
      hijriAdjustment_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 hijriAdjustment = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearHijriAdjustment() {
      
      hijriAdjustment_ = 0;
      onChanged();
      return this;
    }

    private int hijriDate_ ;
    /**
     * <code>int32 hijriDate = 13;</code>
     * @return The hijriDate.
     */
    @java.lang.Override
    public int getHijriDate() {
      return hijriDate_;
    }
    /**
     * <code>int32 hijriDate = 13;</code>
     * @param value The hijriDate to set.
     * @return This builder for chaining.
     */
    public Builder setHijriDate(int value) {
      
      hijriDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 hijriDate = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearHijriDate() {
      
      hijriDate_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object hijriMonth_ = "";
    /**
     * <code>string hijriMonth = 14;</code>
     * @return The hijriMonth.
     */
    public java.lang.String getHijriMonth() {
      java.lang.Object ref = hijriMonth_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hijriMonth_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string hijriMonth = 14;</code>
     * @return The bytes for hijriMonth.
     */
    public com.google.protobuf.ByteString
        getHijriMonthBytes() {
      java.lang.Object ref = hijriMonth_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hijriMonth_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string hijriMonth = 14;</code>
     * @param value The hijriMonth to set.
     * @return This builder for chaining.
     */
    public Builder setHijriMonth(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      hijriMonth_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string hijriMonth = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearHijriMonth() {
      
      hijriMonth_ = getDefaultInstance().getHijriMonth();
      onChanged();
      return this;
    }
    /**
     * <code>string hijriMonth = 14;</code>
     * @param value The bytes for hijriMonth to set.
     * @return This builder for chaining.
     */
    public Builder setHijriMonthBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      hijriMonth_ = value;
      onChanged();
      return this;
    }

    private int hijriYear_ ;
    /**
     * <code>int32 hijriYear = 15;</code>
     * @return The hijriYear.
     */
    @java.lang.Override
    public int getHijriYear() {
      return hijriYear_;
    }
    /**
     * <code>int32 hijriYear = 15;</code>
     * @param value The hijriYear to set.
     * @return This builder for chaining.
     */
    public Builder setHijriYear(int value) {
      
      hijriYear_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 hijriYear = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearHijriYear() {
      
      hijriYear_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest)
  }

  // @@protoc_insertion_point(class_scope:com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest)
  private static final com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest();
  }

  public static com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetDataForMobileAppRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetDataForMobileAppRequest>() {
    @java.lang.Override
    public GetDataForMobileAppRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetDataForMobileAppRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetDataForMobileAppRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetDataForMobileAppRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

