// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mosque-dashboard.proto

package com.mujeeb.mosquedashboard.grpc;

public interface GetDataForMobileAppRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mujeeb.mosquedashboard.grpc.GetDataForMobileAppRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime fajrTime = 1;</code>
   * @return Whether the fajrTime field is set.
   */
  boolean hasFajrTime();
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime fajrTime = 1;</code>
   * @return The fajrTime.
   */
  com.mujeeb.mosquedashboard.grpc.NamazTime getFajrTime();
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime fajrTime = 1;</code>
   */
  com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder getFajrTimeOrBuilder();

  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime zuhrTime = 2;</code>
   * @return Whether the zuhrTime field is set.
   */
  boolean hasZuhrTime();
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime zuhrTime = 2;</code>
   * @return The zuhrTime.
   */
  com.mujeeb.mosquedashboard.grpc.NamazTime getZuhrTime();
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime zuhrTime = 2;</code>
   */
  com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder getZuhrTimeOrBuilder();

  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime asrTime = 3;</code>
   * @return Whether the asrTime field is set.
   */
  boolean hasAsrTime();
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime asrTime = 3;</code>
   * @return The asrTime.
   */
  com.mujeeb.mosquedashboard.grpc.NamazTime getAsrTime();
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime asrTime = 3;</code>
   */
  com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder getAsrTimeOrBuilder();

  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime ishaTime = 4;</code>
   * @return Whether the ishaTime field is set.
   */
  boolean hasIshaTime();
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime ishaTime = 4;</code>
   * @return The ishaTime.
   */
  com.mujeeb.mosquedashboard.grpc.NamazTime getIshaTime();
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime ishaTime = 4;</code>
   */
  com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder getIshaTimeOrBuilder();

  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime jumuaTime = 5;</code>
   * @return Whether the jumuaTime field is set.
   */
  boolean hasJumuaTime();
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime jumuaTime = 5;</code>
   * @return The jumuaTime.
   */
  com.mujeeb.mosquedashboard.grpc.NamazTime getJumuaTime();
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime jumuaTime = 5;</code>
   */
  com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder getJumuaTimeOrBuilder();

  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime ishraqTime = 6;</code>
   * @return Whether the ishraqTime field is set.
   */
  boolean hasIshraqTime();
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime ishraqTime = 6;</code>
   * @return The ishraqTime.
   */
  com.mujeeb.mosquedashboard.grpc.NamazTime getIshraqTime();
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime ishraqTime = 6;</code>
   */
  com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder getIshraqTimeOrBuilder();

  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime duhaTime = 7;</code>
   * @return Whether the duhaTime field is set.
   */
  boolean hasDuhaTime();
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime duhaTime = 7;</code>
   * @return The duhaTime.
   */
  com.mujeeb.mosquedashboard.grpc.NamazTime getDuhaTime();
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime duhaTime = 7;</code>
   */
  com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder getDuhaTimeOrBuilder();

  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime suhurTime = 8;</code>
   * @return Whether the suhurTime field is set.
   */
  boolean hasSuhurTime();
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime suhurTime = 8;</code>
   * @return The suhurTime.
   */
  com.mujeeb.mosquedashboard.grpc.NamazTime getSuhurTime();
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime suhurTime = 8;</code>
   */
  com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder getSuhurTimeOrBuilder();

  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime iftarTime = 9;</code>
   * @return Whether the iftarTime field is set.
   */
  boolean hasIftarTime();
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime iftarTime = 9;</code>
   * @return The iftarTime.
   */
  com.mujeeb.mosquedashboard.grpc.NamazTime getIftarTime();
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime iftarTime = 9;</code>
   */
  com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder getIftarTimeOrBuilder();

  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime screenSaverOnTime = 10;</code>
   * @return Whether the screenSaverOnTime field is set.
   */
  boolean hasScreenSaverOnTime();
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime screenSaverOnTime = 10;</code>
   * @return The screenSaverOnTime.
   */
  com.mujeeb.mosquedashboard.grpc.NamazTime getScreenSaverOnTime();
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime screenSaverOnTime = 10;</code>
   */
  com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder getScreenSaverOnTimeOrBuilder();

  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime screenSaverOffTime = 11;</code>
   * @return Whether the screenSaverOffTime field is set.
   */
  boolean hasScreenSaverOffTime();
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime screenSaverOffTime = 11;</code>
   * @return The screenSaverOffTime.
   */
  com.mujeeb.mosquedashboard.grpc.NamazTime getScreenSaverOffTime();
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.NamazTime screenSaverOffTime = 11;</code>
   */
  com.mujeeb.mosquedashboard.grpc.NamazTimeOrBuilder getScreenSaverOffTimeOrBuilder();

  /**
   * <code>int32 hijriAdjustment = 12;</code>
   * @return The hijriAdjustment.
   */
  int getHijriAdjustment();

  /**
   * <code>int32 hijriDate = 13;</code>
   * @return The hijriDate.
   */
  int getHijriDate();

  /**
   * <code>string hijriMonth = 14;</code>
   * @return The hijriMonth.
   */
  java.lang.String getHijriMonth();
  /**
   * <code>string hijriMonth = 14;</code>
   * @return The bytes for hijriMonth.
   */
  com.google.protobuf.ByteString
      getHijriMonthBytes();

  /**
   * <code>int32 hijriYear = 15;</code>
   * @return The hijriYear.
   */
  int getHijriYear();
}
