// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mosque-dashboard.proto

package com.mujeeb.mosquedashboard.grpc;

@SuppressWarnings("deprecation")
public final class MosqueDashboardProto {
  private MosqueDashboardProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mujeeb_mosquedashboard_grpc_NamazTimeUpdateRequest_descriptor;
static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mujeeb_mosquedashboard_grpc_NamazTimeUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mujeeb_mosquedashboard_grpc_HijriAdjustmentUpdateRequest_descriptor;
static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mujeeb_mosquedashboard_grpc_HijriAdjustmentUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mujeeb_mosquedashboard_grpc_ScreenSaverStateUpdateRequest_descriptor;
static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mujeeb_mosquedashboard_grpc_ScreenSaverStateUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mujeeb_mosquedashboard_grpc_GenericReply_descriptor;
static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mujeeb_mosquedashboard_grpc_GenericReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mujeeb_mosquedashboard_grpc_EmptyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mujeeb_mosquedashboard_grpc_EmptyRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026mosque-dashboard.proto\022\037com.mujeeb.mos" +
      "quedashboard.grpc\"M\n\026NamazTimeUpdateRequ" +
      "est\022\025\n\rnamazTimeName\030\001 \001(\t\022\014\n\004hour\030\002 \001(\005" +
      "\022\016\n\006minute\030\003 \001(\005\"7\n\034HijriAdjustmentUpdat" +
      "eRequest\022\027\n\017hijriAdjustment\030\001 \001(\005\"-\n\035Scr" +
      "eenSaverStateUpdateRequest\022\014\n\004isOn\030\001 \001(\010" +
      "\"9\n\014GenericReply\022\023\n\013description\030\001 \001(\t\022\024\n" +
      "\014responseCode\030\002 \001(\005\"\016\n\014EmptyRequest2\211\005\n\026" +
      "MosqueDashboardService\022{\n\017UpdateNamazTim" +
      "e\0227.com.mujeeb.mosquedashboard.grpc.Nama" +
      "zTimeUpdateRequest\032-.com.mujeeb.mosqueda" +
      "shboard.grpc.GenericReply\"\000\022\207\001\n\025ChangeHi" +
      "jriAdjustment\022=.com.mujeeb.mosquedashboa" +
      "rd.grpc.HijriAdjustmentUpdateRequest\032-.c" +
      "om.mujeeb.mosquedashboard.grpc.GenericRe" +
      "ply\"\000\022k\n\tTestAudio\022-.com.mujeeb.mosqueda" +
      "shboard.grpc.EmptyRequest\032-.com.mujeeb.m" +
      "osquedashboard.grpc.GenericReply\"\000\022\211\001\n\026C" +
      "hangeScreenSaverState\022>.com.mujeeb.mosqu" +
      "edashboard.grpc.ScreenSaverStateUpdateRe" +
      "quest\032-.com.mujeeb.mosquedashboard.grpc." +
      "GenericReply\"\000\022o\n\rRestartSystem\022-.com.mu" +
      "jeeb.mosquedashboard.grpc.EmptyRequest\032-" +
      ".com.mujeeb.mosquedashboard.grpc.Generic" +
      "Reply\"\000B?\n\037com.mujeeb.mosquedashboard.gr" +
      "pcB\024MosqueDashboardProtoP\001\242\002\003HLWb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_mujeeb_mosquedashboard_grpc_NamazTimeUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_mujeeb_mosquedashboard_grpc_NamazTimeUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mujeeb_mosquedashboard_grpc_NamazTimeUpdateRequest_descriptor,
        new java.lang.String[] { "NamazTimeName", "Hour", "Minute", });
    internal_static_com_mujeeb_mosquedashboard_grpc_HijriAdjustmentUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_mujeeb_mosquedashboard_grpc_HijriAdjustmentUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mujeeb_mosquedashboard_grpc_HijriAdjustmentUpdateRequest_descriptor,
        new java.lang.String[] { "HijriAdjustment", });
    internal_static_com_mujeeb_mosquedashboard_grpc_ScreenSaverStateUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_mujeeb_mosquedashboard_grpc_ScreenSaverStateUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mujeeb_mosquedashboard_grpc_ScreenSaverStateUpdateRequest_descriptor,
        new java.lang.String[] { "IsOn", });
    internal_static_com_mujeeb_mosquedashboard_grpc_GenericReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_mujeeb_mosquedashboard_grpc_GenericReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mujeeb_mosquedashboard_grpc_GenericReply_descriptor,
        new java.lang.String[] { "Description", "ResponseCode", });
    internal_static_com_mujeeb_mosquedashboard_grpc_EmptyRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_mujeeb_mosquedashboard_grpc_EmptyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mujeeb_mosquedashboard_grpc_EmptyRequest_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
